name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
              
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          cache: true

      - name: Install dependencies
        run: deno install --frozen

      - name: Build development bundle
        run: deno run build --dev

      - name: Upload development bundle
        uses: actions/upload-artifact@v4
        with:
          name: revenge-bundle-development
          path: dist/revenge.bundle
          if-no-files-found: error

      - name: Clear build
        run: rm -rf dist

      - name: Build production bundle
        run: deno run build

      - name: Upload production bundle
        uses: actions/upload-artifact@v4
        with:
          name: revenge-bundle
          path: dist/revenge.bundle
          if-no-files-found: error